CREATE TABLE lineitem
(
    id          SERIAL,
    lcnt bigint      NOT NULL,
    l_quantity bigint      NOT NULL,
    l_extendedprice numeric  NOT NULL,
    l_discount numeric  NOT NULL,
    l_tax numeric  NOT NULL,
    l_returnflag VARCHAR(2) NOT NULL,
    l_linestatus VARCHAR(2) NOT NULL,
    l_commitdate timestamp NOT NULL,
    l_shipdate timestamp NOT NULL,
    l_receiptdate timestamp NOT NULL,
    l_shipinstruct VARCHAR(255) NOT NULL,
    l_shipmode VARCHAR(255) NOT NULL,
    l_comment VARCHAR(255) NOT NULL,
    o_orderkey bigint      NOT NULL,
    o_status VARCHAR(255) NOT NULL,
    o_totalprice numeric      NOT NULL,
    o_orderdate timestamp NOT NULL,
    o_orderpriority VARCHAR(255) NOT NULL,
    o_clerk VARCHAR(255) NOT NULL,
    o_shippriority  bigint      NOT NULL,
    o_comment VARCHAR(255) NOT NULL,
    c_custkey bigint      NOT NULL,
    c_name VARCHAR(255) NOT NULL,
    c_address VARCHAR(255) NOT NULL,
    c_phone VARCHAR(255) NOT NULL,
    c_acctbal bigint      NOT NULL,
    c_mktsegment VARCHAR(255) NOT NULL,
    c_comment VARCHAR(255) NOT NULL,
    s_suppkey bigint      NOT NULL,
    s_name VARCHAR(255) NOT NULL,
    s_address VARCHAR(255) NOT NULL,
    s_phone VARCHAR(255) NOT NULL,
    s_acctbal bigint      NOT NULL,
    s_comment VARCHAR(255) NOT NULL,
    p_partkey bigint      NOT NULL,
    p_name VARCHAR(255) NOT NULL,
    p_mfgr VARCHAR(255) NOT NULL,
    p_brand VARCHAR(255) NOT NULL,
    p_type VARCHAR(255) NOT NULL,
    p_size numeric  NOT NULL,
    p_container VARCHAR(255) NOT NULL,
    p_retailprice numeric  NOT NULL,
    p_comment VARCHAR(255) NOT NULL,
    ps_quantity bigint      NOT NULL,
    ps_supplycost numeric  NOT NULL,
    ps_comment VARCHAR(255) NOT NULL,

    c_nation_code bigint      NOT NULL,
    c_nation_name VARCHAR(255) NOT NULL,
    c_nation_comment VARCHAR(255) NOT NULL,
    c_region_code bigint      NOT NULL,
    c_region_name VARCHAR(255) NOT NULL,
    c_region_comment VARCHAR(255) NOT NULL,

    s_nation_code bigint      NOT NULL,
    s_nation_name VARCHAR(255) NOT NULL,
    s_nation_comment VARCHAR(255) NOT NULL,
    s_region_code bigint      NOT NULL,
    s_region_name VARCHAR(255) NOT NULL,
    s_region_comment VARCHAR(255) NOT NULL,

    block_id bigint NOT NULL

) partition by LIST (block_id);